"""empty message

Revision ID: 38399143f172
Revises: 
Create Date: 2018-12-25 09:55:28.467658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38399143f172'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lwa', 'cwa',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lwa', 'uwa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lwa', sa.Column('uwa', sa.TEXT(), nullable=True))
    op.alter_column('lwa', 'cwa',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
